DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
DATASETS:
  EVAL_DATASET: market1501
  NAMES: ('msmt17',)
  ROOT_DIR: /home/ljc/datasets
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MGD:
  DISABLE_RANDOM_CROP_ERASE: True
  LOCAL_TOKEN: random
  MASK_FILE_PATH: blobs/msmt17_patch_grounding_mask_calibrated.pkl
  MASK_GATING_THRESH: 0.5
  MASK_GATING_TYPE: offline
  MASK_LOSS_TYPE: bce+dice
  PART_INDEX: [0, 1, 2]
  RMP_LR_MULT: 10.0
  RMP_NUM_HEADS: 8
  RMP_USE_INNER_SHORTCUT: True
  RMP_USE_LAYER_NORM: True
MODEL:
  FREEZE_PATCH_PROJ: True
  I2TCE_LOSS_WEIGHT: 1.0
  ID_LOSS_WEIGHT: 1.0
  MASK_LOSS_WEIGHT: 1.0
  NAME: ViT-B-16
  PCL_LOSS_WEIGHT: 1.0
  STRIDE_SIZE: [16, 16]
OUTPUT_DIR: logs/ms2ma_muva_full-model
PCL:
  CLUSTER_NCE_TEMP: 1.0
  HARD_MEMORY_UPDATE: True
  MEMORY_MOMENTUM: 0.2
  MEMORY_TEMP: 0.01
SOLVER:
  SEED: 1234
  STAGE1:
    BASE_LR: 0.00035
    CHECKPOINT_PERIOD: 120
    IMS_PER_BATCH: 64
    LOG_PERIOD: 50
    LR_MIN: 1e-06
    MAX_EPOCHS: 120
    OPTIMIZER_NAME: Adam
    PRETRAIN: logs/stage1_checkpoints/muva_full_model/msmt_stage1_120.pth
    WARMUP_EPOCHS: 5
    WARMUP_LR_INIT: 1e-05
    WEIGHT_DECAY: 0.0001
  STAGE2:
    BASE_LR: 5e-06
    CHECKPOINT_PERIOD: 60
    EVAL_PERIOD: 60
    GAMMA: 0.1
    IMS_PER_BATCH: 64
    LOG_PERIOD: 50
    MAX_EPOCHS: 60
    OPTIMIZER_NAME: Adam
    STEPS: [30, 50]
    WARMUP_FACTOR: 0.1
    WARMUP_ITERS: 10
    WARMUP_METHOD: linear
    WEIGHT_DECAY: 0.0001
TEST:
  AFTER_BN: True
  FEAT_NORM: True
  IMS_PER_BATCH: 64
  RE_RANKING: False